[package]
name = "arcanus-psw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.12"
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.10.2"
